### ISSUE TITLE
Missing distutils dependence?

### ISSUE THREAD

**Issue by bdrister** [egh/ledger-autosync#15]
After upgrading to 0.3.2, I'm getting this error:

```
Traceback (most recent call last):
  File "/usr/local/bin/ledger-autosync", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/ledgerautosync/cli.py", line 190, in run
    ledger = mk_ledger(ledger_file)
  File "/usr/local/lib/python2.7/dist-packages/ledgerautosync/ledgerwrap.py", line 85, in mk_ledger
    if ((distutils.spawn.find_executable('ledger') is not None) and
AttributeError: 'module' object has no attribute 'spawn'
```

72f9a18b05749f467b2fb1af684470c38cadfd69 seems relevant. Perhaps that introduced a new dependence that's not set up?

**Comment by egh** [comment]
Interesting. What kind of machine are you on?

I've just pushed a fix for a (possibly related) issue with not requiring a recent setuptools (to fix an issue installing on trusty).

**Comment by bdrister** [comment]
Ubuntu 16.04.1 LTS. It's a pretty minimal build that has literally only the bare required software to run this and some other related ledgery stuff, so things that might be coincidentally already set up in a config used for various other purposes might not be so lucky in this case.

**Comment by egh** [comment]
Ah, that seems to make sense. I reproduced in a vm and pushed a new version up to pypi that should fix the issue.

**Comment by egh** [comment]
Thanks for the report!
